apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: knative-chart-ci
spec:
  timeout: 60m
  parameters:
  - name: WORKSPACE
    description: Worksace including any subpaths to work in
    default: /workspace
  steps:
  - image: jenkinsxio/builder-base:{{ .Values.builderTag }}
    name: "continuous-integration"
    args:
    - make
    - build
    resources:
      limits:
        cpu: 0.2
        memory: 128Mi
      requests:
        cpu: 0.1
        memory: 74Mi
    workingDir: "${WORKSPACE}"
