apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: knative-chart-release
spec:
  parameters:
  - name: WORKSPACE
    description: Worksace including any subpaths to work in
    default: /workspace
  steps:
  - image: jenkinsxio/builder-base:{{ .Values.baseTag }}
    env:
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-bot
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-bot
    name: "credentials"
    args:
    - jx
    - step
    - next-version
    - -t
    - --use-git-tag-only
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 74Mi
    workingDir: "${WORKSPACE}"
  - env:
    - name: CHARTMUSEUM_CREDS_USR
      valueFrom:
        secretKeyRef:
          key: BASIC_AUTH_USER
          name: jenkins-x-chartmuseum
    - name: CHARTMUSEUM_CREDS_PSW
      valueFrom:
        secretKeyRef:
          key: BASIC_AUTH_PASS
          name: jenkins-x-chartmuseum
    image: jenkinsxio/builder-base:{{ .Values.baseTag }}
    name: "release"
    args:
    - make
    - release
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 74Mi
    workingDir: "${WORKSPACE}"