apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: knative-deploy
spec:
  timeout: 60m
  parameters:
  - name: ADDON_NAME
    description: Name of the addon to upgrade, leave blank to upgrade all
    default: ""
  steps:
  - args:
    - helm
    - init
    - --client-only
    image: jenkinsxio/builder-base:{{ .Values.builderTag }}
    name: "helm-init"
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 74Mi
  - args:
    - helm
    - repo
    - add
    - jenkins-x
    - http://chartmuseum.jenkins-x.io
    image: jenkinsxio/builder-base:{{ .Values.builderTag }}
    name: "helm-add-repo"
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 74Mi
  - image: jenkinsxio/builder-base:{{ .Values.builderTag }}
    name: "deploy"
    args:
    - jx
    - upgrade
    - addon
    - ${ADDON_NAME}
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 74Mi
